# Projeto 2 — Vacinação COVID-19 vs Internações


## 1. Problema
Como a taxa de vacinação contra COVID-19 se relaciona com as internações nos municípios ao longo do tempo?

## 2. KPI
- Taxa de vacinação (%)
- Taxa de internação (% ou por população)

Objetivo: verificar se existe relação entre aumento da vacinação e redução das internações.

In [1]:

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel("Simulacao_Vacinacao_COVID_Municipios_2021_2024.xlsx")
df.head()

,Município,Ano,População Estimada,Pessoas Vacinadas,Internações por COVID-19
0,São Paulo,2021,6723388,3552667,55384
1,São Paulo,2022,6723388,5498353,37426
2,São Paulo,2023,6723388,3159874,38148
3,São Paulo,2024,6723388,4259911,21131
4,Rio de Janeiro,2021,10826850,4486745,105662

In [2]:

df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Município                 32 non-null     str
 1   Ano                       32 non-null     int64
 2   População Estimada        32 non-null     int64
 3   Pessoas Vacinadas         32 non-null     int64
 4   Internações por COVID-19  32 non-null     int64
dtypes: int64(4), str(1)
memory usage: 1.4 KB

Município                   0
Ano                         0
População Estimada          0
Pessoas Vacinadas           0
Internações por COVID-19    0
dtype: int64

In [5]:

# Ajuste de nomes (exemplo esperado)
df = df.rename(columns={
    "Taxa Vacinação": "Taxa_Vacinacao",
    "Taxa Internações": "Taxa_Internacao"
})

df.head()

,Município,Ano,População Estimada,Pessoas Vacinadas,Internações por COVID-19
0,São Paulo,2021,6723388,3552667,55384
1,São Paulo,2022,6723388,5498353,37426
2,São Paulo,2023,6723388,3159874,38148
3,São Paulo,2024,6723388,4259911,21131
4,Rio de Janeiro,2021,10826850,4486745,105662

In [4]:

# Evolução temporal média
media_ano = df.groupby("Ano")[["Taxa_Vacinacao","Taxa_Internacao"]].mean()
media_ano

KeyError: "Columns not found: 'Taxa_Internacao', 'Taxa_Vacinacao'"

In [ ]:

# Correlação
correlacao = df[["Taxa_Vacinacao","Taxa_Internacao"]].corr()
correlacao

In [ ]:

# Gráfico temporal
media_ano.plot(title="Vacinação vs Internações ao longo do tempo")
plt.show()

In [ ]:

# Scatter plot (ESSENCIAL)
sns.scatterplot(data=df, x="Taxa_Vacinacao", y="Taxa_Internacao")
plt.title("Relação entre Vacinação e Internações")
plt.show()


## 6. Interpretação (Modelo)

Se houver correlação negativa:

> Observa-se que, à medida que a taxa de vacinação aumenta, a taxa de internações tende a diminuir, sugerindo um efeito protetor da vacinação.

Se não houver correlação forte:

> A relação entre vacinação e internações não é claramente linear, indicando que outros fatores podem influenciar as internações.


## 7. Conclusão

A análise permite avaliar se a vacinação impacta diretamente nas internações. Em geral, espera-se uma relação inversa, mas fatores externos também devem ser considerados.

👉 O aluno deve responder claramente: EXISTE ou NÃO relação?